export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAILURE = 'ORDER_DETAILS_FAILURE'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAILURE = 'ORDER_PAY_FAILURE'
export const ORDER_PAY_RESET = 'ORDER_PAY_REQUEST'

export const USER_ORDER_LIST_REQUEST = 'USER_ORDER_LIST_REQUEST'
export const USER_ORDER_LIST_SUCCESS = 'USER_ORDER_LIST_SUCCESS'
export const USER_ORDER_LIST_FAILURE = 'USER_ORDER_LIST_FAILURE'
export const USER_ORDER_LIST_RESET = 'USER_ORDER_LIST_RESET'
